sudo: required
services:
  - docker

before_install:
  - docker build -t zosiaw/docker-react -f Dockerfile.dev .

# Due to a change in how the Jest library works with Create React App, we need to make a small modification:
# script:
#   - docker run USERNAME/docker-react npm run test -- --coverage
script:
  - docker run -e CI=true zosiaw/docker-react npm run test

language: generic 
 
# deploy:
  # provider: elasticbeanstalk
  # region: "us-west-2"
  # app: "docker-react"
  # env: "Docker-env"
  # bucket_name:  "elacticbeanstalk-us-west-2-306476627547"
  # bucket_path: "docker-react"
  # on:
    # branch: master
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: 
    # secure: "$AWS_SECRET_KEY"